swagger: '2.0'
info:
  version: "0.0.1"
  title: Example title
  description: <! foo="[[[Inception]]"><x foo="]foo><script>javascript:alert(1)</script>">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
