swagger: '2.0'
info:
  version: "0.0.1"
  title: Example title
  description: <a href="\x09javascript:javascript:alert(1)" id="fuzzelement1">test</a>

paths:
  /:
    get:
      responses:
        200:
          description: Successful response
