swagger: '2.0'
info:
  version: "0.0.1"
  title: Example title
  description: <input type="text" title="&lt;img src=x onerror=&quot;alert(document.domain)&quot;&gt;">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
